### ISSUE TITLE
Malingsmappa.no - Unencrypted passwords sent via email 

### ISSUE THREAD

**Issue by LarsDjupegot** [redink-no/malingsmappa#1]
The client has requested that we secure the passwords of their clients - they are currently sent out in clear text via. emails. Same as issue: [https://github.com/redink-no/diverse/issues/90](https://github.com/redink-no/diverse/issues/90)

Viktor: Estimate: 4h with simple frontend.

The new practice will be similar to standard wordpress - "Click here to reset password?" and the user is given link to page.

**Comment by LarsDjupegot** [comment]
This is approved.

**Comment by kuliebiakin** [comment]
What text do we need to use for welcome and reset password email?

Now reset password is:

Subject: `Reset password instructions`
Text:
```
Hello user@mail.com!

Someone has requested a link to change your password. You can do this through the link below.

Change my password

If you didn't request this, please ignore this email.

Your password won't change until you access the link above and create a new one.
```

Welcome emal:
Subject: `Malingsmappa- Ny bruker`
Text:
```
Hei og velkommen til malingsmappa.no !

Du kan endre passord inne på din profil.


Hilsen Scanox
```

**Comment by LarsDjupegot** [comment]
Here is text:

Reset password instructions
Subject: Tilbakestilling av passord

```
Hei user@mail.com!
Noen har bedt om å endre passord på din konto. Du kan gjøre dette ved hjelp av linken under.
Endre mitt passord

Hvis du ikke har bedt om endring av ditt passord, kan du se bort fra denne e-posten.
Ditt passord vil ikke endres dersom du ikke selv klikker på linken over, og lager et nytt.

Med vennlig hilsen,
Scanox
```

Welcome email:
Subject: Velkommen til Malingsmappa.no - Ny bruker

```
Du kan nå logge inn, og endre passord inne på din profil.

Med vennlig hilsen,
Scanox
```

**Comment by kuliebiakin** [comment]
Changed in code.
Unfortunately, we do not have stage for this project now.
So, I can push it to prod directly or we can create stage - ~3-4h.

**Comment by LarsDjupegot** [comment]
I will ask the client, and come back to you asap.

**Comment by LarsDjupegot** [comment]
The estimate for creating a stage is approved. Please set up a stage server, and test that the password is not sent by unencrypted e-mail any more.

**Comment by kuliebiakin** [comment]
Stage is created: http://malingsmappa.redink.digital/
Please check.

**Comment by LarsDjupegot** [comment]
This is approved, please push to prod. :)

**Comment by LarsDjupegot** [comment]
Is this pushed? :)

**Comment by kuliebiakin** [comment]
Now yes :)
please check

**Comment by LarsDjupegot** [comment]
Works great, we only need some textual changes:

When clicking "forgotten password" (Glemt passord)
![2018-09-24 11_51_42-http___malingsmappa no_](https://user-images.githubusercontent.com/33456745/45946432-2b57d480-bff1-11e8-87cd-8863fdf3154d.jpg)

![2018-09-24 11_53_11-http___malingsmappa no_](https://user-images.githubusercontent.com/33456745/45946431-2b57d480-bff1-11e8-9bca-db8e67b0f88e.jpg)

When clicking link in email to change password:
![2018-09-24 11_57_03-admin panel _ butinox](https://user-images.githubusercontent.com/33456745/45946430-2b57d480-bff1-11e8-96be-467c66da5c7e.jpg)

Please let me know when this is fixed. :)

**Comment by kuliebiakin** [comment]
Please check on stage

**Comment by LarsDjupegot** [comment]
The changes here looks good, but there is one issue left:

When logged in, and clicking "Endre din profil":

![2018-10-04 13_28_59-http___malingsmappa redink digital_profile](https://user-images.githubusercontent.com/33456745/46472356-31159d00-c7dd-11e8-830b-cbb7655d955d.png)

When changing the password and hitting "enter" or clicking "lagre", nothing happens:

![2018-10-04 13_28_50-http___malingsmappa redink digital_profile](https://user-images.githubusercontent.com/33456745/46472419-67ebb300-c7dd-11e8-86d8-6c087fd04712.png)

Maybe we only need the form under "Endre passord" here?

**Comment by kuliebiakin** [comment]
please check on stage

**Comment by LarsDjupegot** [comment]
Works great, thanks!

**Comment by LarsDjupegot** [comment]
Please push to prod! 👍

**Comment by kuliebiakin** [comment]
on prod

**Comment by LarsDjupegot** [comment]
Great, thanks! 👍
