### ISSUE TITLE
GDPR for http://malingsmappa.no/

### ISSUE THREAD

**Issue by LarsDjupegot** [redink-no/malingsmappa#2]
Please estimate:

- A SSL certificate for malingsmappa.no
- A consent popup, like used on [https://www.jotun.no](https://www.jotun.no) header. With link to the page created in the next step.

![2018-08-29 16_42_49-window](https://user-images.githubusercontent.com/33456745/44795283-9e189000-abaa-11e8-94ff-89b88209e594.jpg)

- A new page for personal data and cookies info, with three separate tabs for Personvernerklæring, vilkår, informasjonskapsler -> like this page: [https://www.jotun.com/no/no/b2c/TermsandconditionsB2C.aspx](https://www.jotun.com/no/no/b2c/TermsandconditionsB2C.aspx)
- Link to this new page containing "Personvernerklæring, vilkår, informasjonskapsler" in footer. 

Client is working on text for us.

**Comment by LarsDjupegot** [comment]
This is approved - but awaiting last feedback on details.

**Comment by LarsDjupegot** [comment]
@kuliebiakin this case issue has been updated. Please re-estimate this task. Would also be great if you could assign a front-end developer for this one, I don't know who will know this cms. ;)

**Comment by kuliebiakin** [comment]
Estimate backend:
- SSL - 3h.
- Popup - 0.5h.
- New page - 5h.
- Link in footer - 0.5h.
Total: 9h.

**Comment by tini2n** [comment]
front-end: 12h

**Comment by kuliebiakin** [comment]
SSL is installed, please check it.

**Comment by LarsDjupegot** [comment]
@Kostiantyn-Nerubenko Could you please test this when it's ready some time next week?

**Comment by kuliebiakin** [comment]
please check on stage

**Comment by LarsDjupegot** [comment]
Please check this guys?

**Comment by kuliebiakin** [comment]
please check

**Comment by LarsDjupegot** [comment]
The logout issue is resolved 👍 , please change the following texts:

**Cookie bar text:**
Ved å godkjenne bruk av informasjonskapsler vil Scanox bruke dataene for å forbedre din brukeropplevelse samt analysere din brukeradferd. Vi bruker informasjonen til å analysere og tilby tilpasset markedsføring i andre kanaler. [Her](http://malingsmappa.redink.digital/privacy) kan du lese mer om Scanox bruk av informasjonskapsler og hvordan du kan endre innstillingene. 

On page: [http://malingsmappa.redink.digital/privacy](http://malingsmappa.redink.digital/privacy)
**Bruk av informasjonskapsler (cookies)**
Set this text to: 
[Bruk av informasjonskapsler.docx](https://github.com/redink-no/malingsmappa/files/2446231/Bruk.av.informasjonskapsler.docx)

**Bruk av informasjonskapsler Second - remove "Second"**
**NOTE:** Set tab title to: Scanox sin personvernerklæring
Set this text to: 
[Scanox Personvernerklæring.docx](https://github.com/redink-no/malingsmappa/files/2446234/Scanox.Personvernerklaering.docx)

**Vilkår**
Set this text to:
[vilkår.docx](https://github.com/redink-no/malingsmappa/files/2446244/vilkar.docx)

**Comment by LarsDjupegot** [comment]
Looks great, just some small adjustments.

Please see screenshot, there are some strange textual errors in "Bruk av informasjonskapsler (cookies)", which are not present in the word document, please just remove the ones marked.

![2018-10-08 16_01_22-http___malingsmappa redink digital_privacy](https://user-images.githubusercontent.com/33456745/46613832-84a52500-cb14-11e8-85ca-a6b1fc95b2cb.png)

Please change Vilkår to the following text: 
[vilkår2.docx](https://github.com/redink-no/malingsmappa/files/2456277/vilkar2.docx)

I think we can close this case after this.

**Comment by kuliebiakin** [comment]
please check

**Comment by LarsDjupegot** [comment]
Great, thanks!

**Comment by LarsDjupegot** [comment]
Please push to prod! 👍

**Comment by kuliebiakin** [comment]
on prod

**Comment by LarsDjupegot** [comment]
Good job! 👍
